version: "3"
services:
  app-api:
    container_name: app-api
    restart: always
    build: .
    env_file: .env
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - app-db
    depends_on:
      - app-db
    networks:
      - app-network
  app-db:
    container_name: app-db
    image: mongo
    volumes:
      - ./docker_scripts/:/docker-entrypoint-initdb.d
    ports:
      - "$MONGO_PORT:$MONGO_PORT"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
