version: "2"
services:
  app-api:
    container_name: app-api
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - app-db
    depends_on:
      - app-db
    networks:
      - db-network
  app-db:
    container_name: app-db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
